name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # Kích hoạt khi bạn đẩy code lên nhánh 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Dùng Node.js 18
      - name: Install dependencies
        run: npm install
      - name: Build
        # Chạy 'npm run build', nó sẽ tự động dùng file vite.config.js (với base: "/")
        run: npm run build 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist # Thư mục 'dist' là nơi chứa web đã build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2